[MN-97] Fixed zero price subscription orders
TerraCycle/spree_product_subscriptions pull request #37
Opened 2023-10-25 15:13 UTC by nuclbain

2023-10-30 13:43 UTC, Ekzosta requested changes

2023-10-30 13:43 UTC, Ekzosta commented on app/models/spree_product_subscriptions/order_decorator.rb
> +                         merge_order.payments.last.source if merge_order
```suggestion
                       elsif merge_order
                         merge_order.payments.last.source
```

2023-10-31 10:01 UTC, Ekzosta approved these changes

2023-11-08 08:06 UTC, storhet approved these changes

2023-11-08 08:06 UTC, merged